export const LEAGUES = [
  {
    id: 2021,
    name: "Premier League",
    crest: "https://crests.football-data.org/PL.png",
    region: "England",
    sofascore: { tournamentId: 17, seasonId: 76986 },
  },
  {
    id: 2014,
    name: "La Liga",
    crest: "https://crests.football-data.org/PD.png",
    region: "Spain",
    sofascore: { tournamentId: 8, seasonId: 77559 },
  },
  {
    id: 2002,
    name: "Bundesliga",
    crest: "https://crests.football-data.org/BL1.png",
    region: "Germany",
    sofascore: { tournamentId: 35, seasonId: 77333 },
  },
  {
    id: 2019,
    name: "Serie A",
    crest: "https://crests.football-data.org/SA.png",
    region: "Italy",
    sofascore: { tournamentId: 23, seasonId: 76457 },
  },
  {
    id: 2015,
    name: "Ligue 1",
    crest: "https://crests.football-data.org/FL1.png",
    region: "France",
    sofascore: { tournamentId: 34, seasonId: 77356 },
  },
  {
    id: 2001,
    name: "Champions League",
    crest: "https://crests.football-data.org/CL.png",
    region: "Europe",
    sofascore: { tournamentId: 7, seasonId: 76953 },
  },
  {
    id: 2000,
    name: "FIFA World Cup",
    crest: "https://crests.football-data.org/qatar.png",
    region: "International",
    sofascore: { tournamentId: 16, seasonId: 58210 },
  },
];
